### ISSUE TITLE
🛠️ FIX : Improve Test Coverage in Complex.t.sol

### ISSUE THREAD

**Issue by 0xpanicError** [BlocSoc-iitr/HorseRiders#2]
### 🛠️ [FIX]

**Description**:
Complex Math lib in Huff do not have 100% test coverage. The functions implemented that are not tested are:
``` solidity
function p_atan2(int256 , int256) returns (int256)
function atan1to1(int256 ) returns (int256)
function ln(int256 , int256) returns (int256)
function sqrt(int256 , int256) returns (int256)
function expZ(int256 , int256) returns (int256 ,int256)
function pow(int256 , int256 , int256) returns (int256 ,int256)
```
Additionally no functions are fuzz tested. 

**Scope**:
Test file for Complex Math functions: `test/Complex.t.sol`

**Objective**:
100% test coverage (both unit and fuzz testing)

**Comment by blueh4mster** [comment]
taking this up from today.
