### ISSUE TITLE
🛠️ FIX : Improve Test Coverage in FFT.t.sol

### ISSUE THREAD

**Issue by 0xpanicError** [BlocSoc-iitr/HorseRiders#3]
### 🛠️ [FIX]
**Description**:
FFT lib in Huff has no tests. Unit test is carried out only for solidity implementation. 

**Scope**:
Test file is in `test/FFT.t.sol`

**Objective**:
100% test coverage for FFT implementation in huff (both unit and fuzz testing). Assume solidity implementation to be correct and assert result from Huff implementation.

**Comment by cy4n1d3-p1x3l** [comment]
I'll try to do them tomorrow.
